### ISSUE TITLE
How can i use in Openwrt 19.07.2

### ISSUE THREAD

**Issue by gzelvis** [Aquantia/AQtion#15]
Can i use this driver (AQC111U) in Openwrt 19.07.2？Or do u have Openwrt special Drivers? Thanks

**Comment by cail** [comment]
You may try backport this driver to your kernel, but we do not provide any support on that.

**Comment by aenertia** [comment]
There are several routers in the wild with aquantia chips (i.e Asus
rt-ax89) who use openwrt build chains and supply sources.

Likely a good place to start.

-Joel
