### ISSUE TITLE
link detection broken

### ISSUE THREAD

**Issue by tbludau** [Aquantia/AQtion#2]
Hello,

under Ubuntu 18.04. and kernel 4.15.16-041516-generic i've a problem to integrate the atlantic driver in the System under one system. (AMD N54L).

When configured and integrated as boot mechanism in initrd it is not possible for the driver to find a link of the network card. 

The workaround at the moment is to load the kernel version of the atlantic driver 1.6.13.0-kern (which is broken for me when used under load), then rmmod atlantic and insmod atlantic.ko from the 2.0.6 version of this driver. 
This is the only situation i got the network link of the network card.

With the delivered kernel driver the link works normally.

Best Regards
Thomas

**Comment by cail** [comment]
Here is a root cause and the patch:
https://bugzilla.kernel.org/show_bug.cgi?id=199177
